/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// UserGroupSpecApplyConfiguration represents a declarative configuration of the UserGroupSpec type for use
// with apply.
type UserGroupSpecApplyConfiguration struct {
	Password   *string  `json:"password,omitempty"`
	Namespaces []string `json:"namespaces,omitempty"`
}

// UserGroupSpecApplyConfiguration constructs a declarative configuration of the UserGroupSpec type for use with
// apply.
func UserGroupSpec() *UserGroupSpecApplyConfiguration {
	return &UserGroupSpecApplyConfiguration{}
}

// WithPassword sets the Password field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Password field is set to the value of the last call.
func (b *UserGroupSpecApplyConfiguration) WithPassword(value string) *UserGroupSpecApplyConfiguration {
	b.Password = &value
	return b
}

// WithNamespaces adds the given value to the Namespaces field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Namespaces field.
func (b *UserGroupSpecApplyConfiguration) WithNamespaces(values ...string) *UserGroupSpecApplyConfiguration {
	for i := range values {
		b.Namespaces = append(b.Namespaces, values[i])
	}
	return b
}
