kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: disk-default
    annotations:
        storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
parameters:
    dataEngine: v1
    dataLocality: disabled
    disableRevisionCounter: 'true'
    diskSelector: disk-default
    fromBackup: ''
    fsType: ext4
    numberOfReplicas: '1'
    staleReplicaTimeout: '300'
    unmapMarkSnapChainRemoved: ignored
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate