kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: default-volume
    namespace: default
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
    storageClassName: disk-default
    volumeMode: Filesystem

