# .cnb.yml
1.1.*:
  tag_push:
    - env:
        - KO_DEFAULTBASEIMAGE=ccr.ccs.tencentyun.com/afan-public/ubuntu:24.04-offlineui
        - KO_DOCKER_REPO=ccr.ccs.tencentyun.com/afan-public/w7panel-dev
        # export KO_DEFAULTBASEIMAGE=ccr.ccs.tencentyun.com/afan-public/ubuntu:24.04-offlineui && export KO_DOCKER_REPO=ccr.ccs.tencentyun.com/afan-public/w7panel 
      imports:
        - https://cnb.cool/i0358/mykey/-/blob/main/218.yml
      docker:
        # 通过此参数控制使用的 Dockerfile 构建镜像必须公开
        image: ccr.ccs.tencentyun.com/afan-public/ubuntu:go-build
        volumes: 
          - /home/workspace/.cache:read-write
          - /root/.cache:read-write
      stages:
       
        - name: upzip
          script: cd ./kodata/ && unzip -o ./kui.zip
        # - name: unzipwebdav
        #   script: cd ./kodata/plugin/webdav && unzip -o ./webdav.zip
        - name: logo
          script: mv ./kodata/logo.png ./kodata/assets/logo.png
        - name: login
          script: /root/go/bin/ko login docker.cnb.cool -u cnb -p ${CNB_TOKEN}
        # - name: build-dev
        #   script: export KO_DOCKER_REPO=ccr.ccs.tencentyun.com/afan-public/w7panel-dev && export KO_DEFAULTBASEIMAGE=ccr.ccs.tencentyun.com/afan-public/ubuntu:24.04-offlineui && /root/go/bin/ko build --bare --tags=${CNB_BRANCH} --tag-only --sbom=none --platform=all
          # 构建镜像，并推送到镜像仓库
        - name: build
          script:  export KO_DOCKER_REPO=docker.cnb.cool/i0358/w7panel && export KO_DEFAULTBASEIMAGE=ccr.ccs.tencentyun.com/afan-public/ubuntu:24.04-offlineui && /root/go/bin/ko build --bare --tags=${CNB_BRANCH} --tag-only --sbom=none --platform=all

        - name: publish
          script: echo $HELM_KUBECAFILE_BASE64 | base64 -d >/tmp/ca.crt && ./publish.sh
$:
  vscode:
    - runner:
        cpus: 8
      docker:
        build: .ide/Dockerfile
      services:
        - vscode
        - docker
      stages:
        - name: ls
          script: ls -al
