/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	mcpserverv1alpha1 "gitee.com/we7coreteam/k8s-offline/k8s/pkg/apis/mcpserver/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// McpServerLister helps list McpServers.
// All objects returned here must be treated as read-only.
type McpServerLister interface {
	// List lists all McpServers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*mcpserverv1alpha1.McpServer, err error)
	// McpServers returns an object that can list and get McpServers.
	McpServers(namespace string) McpServerNamespaceLister
	McpServerListerExpansion
}

// mcpServerLister implements the McpServerLister interface.
type mcpServerLister struct {
	listers.ResourceIndexer[*mcpserverv1alpha1.McpServer]
}

// NewMcpServerLister returns a new McpServerLister.
func NewMcpServerLister(indexer cache.Indexer) McpServerLister {
	return &mcpServerLister{listers.New[*mcpserverv1alpha1.McpServer](indexer, mcpserverv1alpha1.Resource("mcpserver"))}
}

// McpServers returns an object that can list and get McpServers.
func (s *mcpServerLister) McpServers(namespace string) McpServerNamespaceLister {
	return mcpServerNamespaceLister{listers.NewNamespaced[*mcpserverv1alpha1.McpServer](s.ResourceIndexer, namespace)}
}

// McpServerNamespaceLister helps list and get McpServers.
// All objects returned here must be treated as read-only.
type McpServerNamespaceLister interface {
	// List lists all McpServers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*mcpserverv1alpha1.McpServer, err error)
	// Get retrieves the McpServer from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*mcpserverv1alpha1.McpServer, error)
	McpServerNamespaceListerExpansion
}

// mcpServerNamespaceLister implements the McpServerNamespaceLister
// interface.
type mcpServerNamespaceLister struct {
	listers.ResourceIndexer[*mcpserverv1alpha1.McpServer]
}
