/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisuserv1alpha1 "gitee.com/we7coreteam/k8s-offline/k8s/pkg/apis/user/v1alpha1"
	versioned "gitee.com/we7coreteam/k8s-offline/k8s/pkg/client/user/clientset/versioned"
	internalinterfaces "gitee.com/we7coreteam/k8s-offline/k8s/pkg/client/user/informers/externalversions/internalinterfaces"
	userv1alpha1 "gitee.com/we7coreteam/k8s-offline/k8s/pkg/client/user/listers/user/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// UserGroupInformer provides access to a shared informer and lister for
// UserGroups.
type UserGroupInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() userv1alpha1.UserGroupLister
}

type userGroupInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewUserGroupInformer constructs a new informer for UserGroup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewUserGroupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredUserGroupInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredUserGroupInformer constructs a new informer for UserGroup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredUserGroupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UserV1alpha1().UserGroups(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UserV1alpha1().UserGroups(namespace).Watch(context.TODO(), options)
			},
		},
		&apisuserv1alpha1.UserGroup{},
		resyncPeriod,
		indexers,
	)
}

func (f *userGroupInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredUserGroupInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *userGroupInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisuserv1alpha1.UserGroup{}, f.defaultInformer)
}

func (f *userGroupInformer) Lister() userv1alpha1.UserGroupLister {
	return userv1alpha1.NewUserGroupLister(f.Informer().GetIndexer())
}
