/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	userv1alpha1 "gitee.com/we7coreteam/k8s-offline/k8s/pkg/apis/user/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// UserGroupLister helps list UserGroups.
// All objects returned here must be treated as read-only.
type UserGroupLister interface {
	// List lists all UserGroups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*userv1alpha1.UserGroup, err error)
	// UserGroups returns an object that can list and get UserGroups.
	UserGroups(namespace string) UserGroupNamespaceLister
	UserGroupListerExpansion
}

// userGroupLister implements the UserGroupLister interface.
type userGroupLister struct {
	listers.ResourceIndexer[*userv1alpha1.UserGroup]
}

// NewUserGroupLister returns a new UserGroupLister.
func NewUserGroupLister(indexer cache.Indexer) UserGroupLister {
	return &userGroupLister{listers.New[*userv1alpha1.UserGroup](indexer, userv1alpha1.Resource("usergroup"))}
}

// UserGroups returns an object that can list and get UserGroups.
func (s *userGroupLister) UserGroups(namespace string) UserGroupNamespaceLister {
	return userGroupNamespaceLister{listers.NewNamespaced[*userv1alpha1.UserGroup](s.ResourceIndexer, namespace)}
}

// UserGroupNamespaceLister helps list and get UserGroups.
// All objects returned here must be treated as read-only.
type UserGroupNamespaceLister interface {
	// List lists all UserGroups in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*userv1alpha1.UserGroup, err error)
	// Get retrieves the UserGroup from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*userv1alpha1.UserGroup, error)
	UserGroupNamespaceListerExpansion
}

// userGroupNamespaceLister implements the UserGroupNamespaceLister
// interface.
type userGroupNamespaceLister struct {
	listers.ResourceIndexer[*userv1alpha1.UserGroup]
}
