/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	mcpserverv1alpha1 "gitee.com/we7coreteam/k8s-offline/k8s/pkg/apis/mcpserver/v1alpha1"
	applyconfigurationmcpserverv1alpha1 "gitee.com/we7coreteam/k8s-offline/k8s/pkg/client/mcpserver/applyconfiguration/mcpserver/v1alpha1"
	scheme "gitee.com/we7coreteam/k8s-offline/k8s/pkg/client/mcpserver/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// McpServersGetter has a method to return a McpServerInterface.
// A group's client should implement this interface.
type McpServersGetter interface {
	McpServers(namespace string) McpServerInterface
}

// McpServerInterface has methods to work with McpServer resources.
type McpServerInterface interface {
	Create(ctx context.Context, mcpServer *mcpserverv1alpha1.McpServer, opts v1.CreateOptions) (*mcpserverv1alpha1.McpServer, error)
	Update(ctx context.Context, mcpServer *mcpserverv1alpha1.McpServer, opts v1.UpdateOptions) (*mcpserverv1alpha1.McpServer, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*mcpserverv1alpha1.McpServer, error)
	List(ctx context.Context, opts v1.ListOptions) (*mcpserverv1alpha1.McpServerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *mcpserverv1alpha1.McpServer, err error)
	Apply(ctx context.Context, mcpServer *applyconfigurationmcpserverv1alpha1.McpServerApplyConfiguration, opts v1.ApplyOptions) (result *mcpserverv1alpha1.McpServer, err error)
	McpServerExpansion
}

// mcpServers implements McpServerInterface
type mcpServers struct {
	*gentype.ClientWithListAndApply[*mcpserverv1alpha1.McpServer, *mcpserverv1alpha1.McpServerList, *applyconfigurationmcpserverv1alpha1.McpServerApplyConfiguration]
}

// newMcpServers returns a McpServers
func newMcpServers(c *McpserverV1alpha1Client, namespace string) *mcpServers {
	return &mcpServers{
		gentype.NewClientWithListAndApply[*mcpserverv1alpha1.McpServer, *mcpserverv1alpha1.McpServerList, *applyconfigurationmcpserverv1alpha1.McpServerApplyConfiguration](
			"mcpservers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *mcpserverv1alpha1.McpServer { return &mcpserverv1alpha1.McpServer{} },
			func() *mcpserverv1alpha1.McpServerList { return &mcpserverv1alpha1.McpServerList{} },
		),
	}
}
