/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AppGroupSpecApplyConfiguration represents a declarative configuration of the AppGroupSpec type for use
// with apply.
type AppGroupSpecApplyConfiguration struct {
	Identifie        *string                       `json:"identifie,omitempty"`
	Type             *string                       `json:"type,omitempty"`
	Version          *string                       `json:"version,omitempty"`
	UpgradingVersion *string                       `json:"upgradingVersion,omitempty"`
	Title            *string                       `json:"title,omitempty"`
	Logo             *string                       `json:"logo,omitempty"`
	Description      *string                       `json:"description,omitempty"`
	Suffix           *string                       `json:"suffix,omitempty"`
	ZpkUrl           *string                       `json:"zpkUrl,omitempty"`
	HelmConfig       *HelmConfigApplyConfiguration `json:"helmConfig,omitempty"`
	IsHelm           *bool                         `json:"isHelm,omitempty"`
}

// AppGroupSpecApplyConfiguration constructs a declarative configuration of the AppGroupSpec type for use with
// apply.
func AppGroupSpec() *AppGroupSpecApplyConfiguration {
	return &AppGroupSpecApplyConfiguration{}
}

// WithIdentifie sets the Identifie field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Identifie field is set to the value of the last call.
func (b *AppGroupSpecApplyConfiguration) WithIdentifie(value string) *AppGroupSpecApplyConfiguration {
	b.Identifie = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *AppGroupSpecApplyConfiguration) WithType(value string) *AppGroupSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *AppGroupSpecApplyConfiguration) WithVersion(value string) *AppGroupSpecApplyConfiguration {
	b.Version = &value
	return b
}

// WithUpgradingVersion sets the UpgradingVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpgradingVersion field is set to the value of the last call.
func (b *AppGroupSpecApplyConfiguration) WithUpgradingVersion(value string) *AppGroupSpecApplyConfiguration {
	b.UpgradingVersion = &value
	return b
}

// WithTitle sets the Title field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Title field is set to the value of the last call.
func (b *AppGroupSpecApplyConfiguration) WithTitle(value string) *AppGroupSpecApplyConfiguration {
	b.Title = &value
	return b
}

// WithLogo sets the Logo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Logo field is set to the value of the last call.
func (b *AppGroupSpecApplyConfiguration) WithLogo(value string) *AppGroupSpecApplyConfiguration {
	b.Logo = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *AppGroupSpecApplyConfiguration) WithDescription(value string) *AppGroupSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithSuffix sets the Suffix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suffix field is set to the value of the last call.
func (b *AppGroupSpecApplyConfiguration) WithSuffix(value string) *AppGroupSpecApplyConfiguration {
	b.Suffix = &value
	return b
}

// WithZpkUrl sets the ZpkUrl field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ZpkUrl field is set to the value of the last call.
func (b *AppGroupSpecApplyConfiguration) WithZpkUrl(value string) *AppGroupSpecApplyConfiguration {
	b.ZpkUrl = &value
	return b
}

// WithHelmConfig sets the HelmConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HelmConfig field is set to the value of the last call.
func (b *AppGroupSpecApplyConfiguration) WithHelmConfig(value *HelmConfigApplyConfiguration) *AppGroupSpecApplyConfiguration {
	b.HelmConfig = value
	return b
}

// WithIsHelm sets the IsHelm field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsHelm field is set to the value of the last call.
func (b *AppGroupSpecApplyConfiguration) WithIsHelm(value bool) *AppGroupSpecApplyConfiguration {
	b.IsHelm = &value
	return b
}
