/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AppGroupStatusApplyConfiguration represents a declarative configuration of the AppGroupStatus type for use
// with apply.
type AppGroupStatusApplyConfiguration struct {
	Items          []AppGroupItemStatusApplyConfiguration `json:"items,omitempty"`
	DeployItems    []DeployItemApplyConfiguration         `json:"deployInfo,omitempty"`
	DeployStatus   *string                                `json:"deployStatus,omitempty"`
	Ready          *bool                                  `json:"ready,omitempty"`
	IsZeroReplicas *bool                                  `json:"isZeroReplicas,omitempty"`
}

// AppGroupStatusApplyConfiguration constructs a declarative configuration of the AppGroupStatus type for use with
// apply.
func AppGroupStatus() *AppGroupStatusApplyConfiguration {
	return &AppGroupStatusApplyConfiguration{}
}

// WithItems adds the given value to the Items field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Items field.
func (b *AppGroupStatusApplyConfiguration) WithItems(values ...*AppGroupItemStatusApplyConfiguration) *AppGroupStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithItems")
		}
		b.Items = append(b.Items, *values[i])
	}
	return b
}

// WithDeployItems adds the given value to the DeployItems field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DeployItems field.
func (b *AppGroupStatusApplyConfiguration) WithDeployItems(values ...*DeployItemApplyConfiguration) *AppGroupStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDeployItems")
		}
		b.DeployItems = append(b.DeployItems, *values[i])
	}
	return b
}

// WithDeployStatus sets the DeployStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeployStatus field is set to the value of the last call.
func (b *AppGroupStatusApplyConfiguration) WithDeployStatus(value string) *AppGroupStatusApplyConfiguration {
	b.DeployStatus = &value
	return b
}

// WithReady sets the Ready field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ready field is set to the value of the last call.
func (b *AppGroupStatusApplyConfiguration) WithReady(value bool) *AppGroupStatusApplyConfiguration {
	b.Ready = &value
	return b
}

// WithIsZeroReplicas sets the IsZeroReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsZeroReplicas field is set to the value of the last call.
func (b *AppGroupStatusApplyConfiguration) WithIsZeroReplicas(value bool) *AppGroupStatusApplyConfiguration {
	b.IsZeroReplicas = &value
	return b
}
