/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	userv1alpha1 "gitee.com/we7coreteam/k8s-offline/k8s/pkg/apis/user/v1alpha1"
	applyconfigurationuserv1alpha1 "gitee.com/we7coreteam/k8s-offline/k8s/pkg/client/user/applyconfiguration/user/v1alpha1"
	scheme "gitee.com/we7coreteam/k8s-offline/k8s/pkg/client/user/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// UserGroupsGetter has a method to return a UserGroupInterface.
// A group's client should implement this interface.
type UserGroupsGetter interface {
	UserGroups(namespace string) UserGroupInterface
}

// UserGroupInterface has methods to work with UserGroup resources.
type UserGroupInterface interface {
	Create(ctx context.Context, userGroup *userv1alpha1.UserGroup, opts v1.CreateOptions) (*userv1alpha1.UserGroup, error)
	Update(ctx context.Context, userGroup *userv1alpha1.UserGroup, opts v1.UpdateOptions) (*userv1alpha1.UserGroup, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*userv1alpha1.UserGroup, error)
	List(ctx context.Context, opts v1.ListOptions) (*userv1alpha1.UserGroupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *userv1alpha1.UserGroup, err error)
	Apply(ctx context.Context, userGroup *applyconfigurationuserv1alpha1.UserGroupApplyConfiguration, opts v1.ApplyOptions) (result *userv1alpha1.UserGroup, err error)
	UserGroupExpansion
}

// userGroups implements UserGroupInterface
type userGroups struct {
	*gentype.ClientWithListAndApply[*userv1alpha1.UserGroup, *userv1alpha1.UserGroupList, *applyconfigurationuserv1alpha1.UserGroupApplyConfiguration]
}

// newUserGroups returns a UserGroups
func newUserGroups(c *UserV1alpha1Client, namespace string) *userGroups {
	return &userGroups{
		gentype.NewClientWithListAndApply[*userv1alpha1.UserGroup, *userv1alpha1.UserGroupList, *applyconfigurationuserv1alpha1.UserGroupApplyConfiguration](
			"usergroups",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *userv1alpha1.UserGroup { return &userv1alpha1.UserGroup{} },
			func() *userv1alpha1.UserGroupList { return &userv1alpha1.UserGroupList{} },
		),
	}
}
