/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// McpServerSpecApplyConfiguration represents a declarative configuration of the McpServerSpec type for use
// with apply.
type McpServerSpecApplyConfiguration struct {
	Command *string           `json:"command,omitempty"`
	Args    []string          `json:"args,omitempty"`
	Env     map[string]string `json:"env,omitempty"`
	Url     *string           `json:"url,omitempty"`
	Domain  *string           `json:"domain,omitempty"`
}

// McpServerSpecApplyConfiguration constructs a declarative configuration of the McpServerSpec type for use with
// apply.
func McpServerSpec() *McpServerSpecApplyConfiguration {
	return &McpServerSpecApplyConfiguration{}
}

// WithCommand sets the Command field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Command field is set to the value of the last call.
func (b *McpServerSpecApplyConfiguration) WithCommand(value string) *McpServerSpecApplyConfiguration {
	b.Command = &value
	return b
}

// WithArgs adds the given value to the Args field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Args field.
func (b *McpServerSpecApplyConfiguration) WithArgs(values ...string) *McpServerSpecApplyConfiguration {
	for i := range values {
		b.Args = append(b.Args, values[i])
	}
	return b
}

// WithEnv puts the entries into the Env field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Env field,
// overwriting an existing map entries in Env field with the same key.
func (b *McpServerSpecApplyConfiguration) WithEnv(entries map[string]string) *McpServerSpecApplyConfiguration {
	if b.Env == nil && len(entries) > 0 {
		b.Env = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Env[k] = v
	}
	return b
}

// WithUrl sets the Url field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Url field is set to the value of the last call.
func (b *McpServerSpecApplyConfiguration) WithUrl(value string) *McpServerSpecApplyConfiguration {
	b.Url = &value
	return b
}

// WithDomain sets the Domain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domain field is set to the value of the last call.
func (b *McpServerSpecApplyConfiguration) WithDomain(value string) *McpServerSpecApplyConfiguration {
	b.Domain = &value
	return b
}
