/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BindingsApplyConfiguration represents a declarative configuration of the Bindings type for use
// with apply.
type BindingsApplyConfiguration struct {
	Framework         *string                  `json:"framework,omitempty"`
	IsDefaultRegister *int                     `json:"is_default_register,omitempty"`
	Location          *string                  `json:"location,omitempty"`
	Support           *string                  `json:"support,omitempty"`
	Menu              []MenuApplyConfiguration `json:"menu,omitempty"`
	Name              *string                  `json:"name,omitempty"`
	Status            *int                     `json:"status,omitempty"`
	Title             *string                  `json:"title,omitempty"`
}

// BindingsApplyConfiguration constructs a declarative configuration of the Bindings type for use with
// apply.
func Bindings() *BindingsApplyConfiguration {
	return &BindingsApplyConfiguration{}
}

// WithFramework sets the Framework field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Framework field is set to the value of the last call.
func (b *BindingsApplyConfiguration) WithFramework(value string) *BindingsApplyConfiguration {
	b.Framework = &value
	return b
}

// WithIsDefaultRegister sets the IsDefaultRegister field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsDefaultRegister field is set to the value of the last call.
func (b *BindingsApplyConfiguration) WithIsDefaultRegister(value int) *BindingsApplyConfiguration {
	b.IsDefaultRegister = &value
	return b
}

// WithLocation sets the Location field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Location field is set to the value of the last call.
func (b *BindingsApplyConfiguration) WithLocation(value string) *BindingsApplyConfiguration {
	b.Location = &value
	return b
}

// WithSupport sets the Support field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Support field is set to the value of the last call.
func (b *BindingsApplyConfiguration) WithSupport(value string) *BindingsApplyConfiguration {
	b.Support = &value
	return b
}

// WithMenu adds the given value to the Menu field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Menu field.
func (b *BindingsApplyConfiguration) WithMenu(values ...*MenuApplyConfiguration) *BindingsApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMenu")
		}
		b.Menu = append(b.Menu, *values[i])
	}
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BindingsApplyConfiguration) WithName(value string) *BindingsApplyConfiguration {
	b.Name = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *BindingsApplyConfiguration) WithStatus(value int) *BindingsApplyConfiguration {
	b.Status = &value
	return b
}

// WithTitle sets the Title field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Title field is set to the value of the last call.
func (b *BindingsApplyConfiguration) WithTitle(value string) *BindingsApplyConfiguration {
	b.Title = &value
	return b
}
