/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// MicroAppConfigApplyConfiguration represents a declarative configuration of the MicroAppConfig type for use
// with apply.
type MicroAppConfigApplyConfiguration struct {
	Props map[string]string `json:"props,omitempty"`
}

// MicroAppConfigApplyConfiguration constructs a declarative configuration of the MicroAppConfig type for use with
// apply.
func MicroAppConfig() *MicroAppConfigApplyConfiguration {
	return &MicroAppConfigApplyConfiguration{}
}

// WithProps puts the entries into the Props field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Props field,
// overwriting an existing map entries in Props field with the same key.
func (b *MicroAppConfigApplyConfiguration) WithProps(entries map[string]string) *MicroAppConfigApplyConfiguration {
	if b.Props == nil && len(entries) > 0 {
		b.Props = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Props[k] = v
	}
	return b
}
